# This a Github Action for building Marlin Firmware.

name: Build Marlin - Ender 2 Pro

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: bugfix-2.1.x
        description: Marlin branch to build, eg. release-2.1.2
      release_tag:
        required: true
        description: Release tag
      release_name:
        description: Release name

env:
  BOARD: STM32F103RE_creality
  CONFIG_DIR: Configurations/config/examples/Creality/Ender-2 Pro/CrealityV423
        
jobs:
  build_and_release:
    name: Build and release firmware
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile firmware
        run: |
          docker run \
            -u root:root \
            -e USE_REPO=https://github.com/MarlinFirmware/Marlin \
            -e BOARD=${{ env.BOARD }} \
            -e USE_BRANCH=${{ github.event.inputs.branch }} \
            -v "$(pwd)/build":/home/platformio/build \
            -v "$(pwd)/${{ env.CONFIG_DIR }}":/home/platformio/CustomConfiguration \
            frealmyr/marlin-build:latest

      - name: Release firmware
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.release_name }}
          tag_name: ${{ github.event.inputs.release_tag }}
          fail_on_unmatched_files: true
          files: "*"
